title: Adam's Blog

author: Adam Muzaffar Abd Razak
email: adam.abd-razak@outlook.my

plugins:
  - jekyll-feed
  - jekyll-seo-tag

description: >
  Technical insights at the intersection of climate science and emerging technologies.

theme: minima

minima:
  skin: classic
  nav_pages:
    - about.md
  show_excerpts: true
  github_username: adamabd-razak
  hide_site_feed_link: true
